#docker-compose.yml (for develop test)
# in cedcd project directory
# build image  : docker build -t cedcd_frontend:latest -f docker/frontend.dockerfile .
# build image  : docker build -t cedcd_backend:latest -f docker/backend.dockerfile .
# after contaier (frontend) is created -- for local test
# --- docker cp cedcd-frontend:/var/www/html/cedcd/. client/build

services:
  backend:
    container_name: cedcd-backend
    image: cedcd_backend:latest
    volumes: 
      - ${PWD}/logs/:/deploy/logs/
      - ${PWD}/data/:/deploy/data/
      - ${PWD}/temp/:/deploy/temp/
     # - ${PWD}/client/build/:/deploy/server/client/www/
      - ${PWD}/server/config/cedcd.settings:/deploy/server/config/cedcd.settings
    ports:
      - "8000:8221"
    environment:
      - NODE_ENV=development 
    restart: always

  
  frontend:
    container_name: cedcd-frontend
    image: cedcd_frontend:latest
    volumes: 
      - ${PWD}/apache_logs/:/var/log/httpd/
      - ${PWD}/data/:/deploy/data/
      - ${PWD}/docker/cedcd_frontend.conf:/etc/httpd/conf.d/cedcd.conf
    ports:
      - "8010:80"
    depends_on:
      - backend
    restart: always
    environment:
      - API_HOST=http://backend:8221
  